# Generated by Django 5.1.4 on 2025-01-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='Name not given'),
        ),
    ]
